version: "3.8"
services:
  client:
    stdin_open: true
    image: neel9248/toolbox:client
    ports:
      - "3000:3000"
    volumes:
      - "/DataScienceToolbox/datasciencetoolbox/node_modules"
      - ".:/DataScienceToolbox/datasciencetoolbox"
  gitapp:
    stdin_open: true
    image: neel9248/toolbox:gitapp
    ports:
      - "9901:6901"
      - "5901:5901"
  # spyderappnew:
  #   stdin_open: true
  #   image: 4e3dadc3963c
  #   ports:
  #     - "3002:3000"
  jupyterapp:
    stdin_open: true
    image: neel9248/toolbox:jupyterapp 
    ports:
      - "8888:8888"
  orangeapp:
    stdin_open: true
    image: neel9248/toolbox:orangeapp
    ports:
      - "127.0.0.1:5801:5801"
      - "127.0.0.1:6901:6901"
    environment: 
      - password=orange
  tensorflowapp:
    stdin_open: true
    image: neel9248/toolbox:tensorflowapp
    ports:
      - "3005:3005"
  rstudioapp:
    stdin_open: true
    image: neel9248/toolbox:rstudioapp
    ports:
      - "8787:8787" 
    environment: 
      - DISABLE_AUTH=true
  vscodeapp:
    stdin_open: true
    image: neel9248/toolbox:vscodeapp
    ports:
      - "1000:8080"
    # volumes:
    #   - "$(pwd)/data:/data"
    #   - "$(pwd)/code:/code"
  hadoopapp:
    stdin_open: true
    image: neel9248/toolbox:hadoopapp 
    ports:
      - "8042:8042"
      - "8043:8043"
      - "19888:19888"
      - "50071:50071"
      - "50075:50075"
  sparkapp:
    stdin_open: true
    image: neel9248/toolbox:sparkapp
    environment: 
      - SPARK_MODE=master
  markdownapp:
    stdin_open: true
    image: neel9248/toolbox:markdownapp
    ports:
      - "12345:80"
  tableauapp:
    stdin_open: true
    image: neel9248/toolbox:tableauapp
  sonarqubeapp:
    stdin_open: true
    image: neel9248/toolbox:sonarqubeapp
    ports:
      - "9000:9000"
      - "9092:9092"
  # sonarscannerapp:
  #   stdin_open: true
  #   image: 2885105558a6
  #   depends_on:
  #     - sonarqubeapp
  #   restart: on-failure
  #   # command: >
  #   #   /bin/bash "
  #   #     sleep 50;"
  #   environment: 
  #     - SONAR_HOST_URL=http://host.docker.internal:9000
  #   volumes: 
  #     - "./:/Users/neeltrivedi/code/cs1660/final-project/DataScienceToolbox/datasciencetoolbox/sonarscanner"
    # deploy:
    #   restart_policy:
    #       condition: on-failure
    #       delay: 20s
    #       max_attempts: 5
    #       window: 120s
# networks:
#   sonar:
#     external:
#       name: sonar


      


  

    
  
    
  